---
- name: " GET DEVICES"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: "RETRIEVE DEVICES AND SET AS FACT"
      ansible.builtin.set_fact:
        nautobot_devices:
          "{{ query('networktocode.nautobot.lookup', 'devices', api_filter='name=ams01-leaf-01') }}"

    - name: "LOOP OVER DEVICES AND DEBUG NAME OF EACH DEVICE"
      ansible.builtin.debug:
        msg: "The name of the device is {{ item.value.name }}."
      loop: "{{ nautobot_devices }}"
