---
- name: "ADD DEVICES"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    nautobot_url: "{{ lookup('env', 'NAUTOBOT_URL') }}"
    nautobot_token: "{{ lookup('env', 'NAUTOBOT_TOKEN') }}"

  tasks:
    # If device names are not FQDNs, use the primary_ip4 or primary_ip6
    # parameters in this task, but ensure the IPs are are first added
    # to Nautobot and assigned to an interface.
    # Example:  primary_ip4: "10.0.0.15/24"

    - name: "ADD DEVICES"
      networktocode.nautobot.device:
        url: "{{ nautobot_url }}"
        token: "{{ nautobot_token }}"
        name: "{{ device['name'] }}"
        role: "{{ device['role'] }}"
        device_type: "{{ device['device_type'] }}"
        platform: "{{ device['platform'] }}"
        location: "{{ device['location'] }}"
        status: "{{ device['status'] }}"
        state: present
      loop_control:
        loop_var: device
      loop:
        - name: "nyc-bb-01.infra.ntc.com"
          role: "backbone"
          device_type: "vMX"
          platform: "Juniper Junos"
          location: "New York City"
          status: "Active"
        - name: "nyc-rtr-01.infra.ntc.com"
          role: "router"
          device_type: "vMX"
          platform: "Juniper Junos"
          location: "New York City"
          status: "Active"
        - name: "nyc-rtr-02.infra.ntc.com"
          role: "router"
          device_type: "vMX"
          platform: "Juniper Junos"
          location: "New York City"
          status: "Active"
        - name: "nyc-spine-01.infra.ntc.com"
          role: "spine"
          device_type: "vEOS"
          platform: "Arista EOS"
          location: "New York City"
          status: "Active"
        - name: "nyc-spine-02.infra.ntc.com"
          role: "spine"
          device_type: "vEOS"
          platform: "Arista EOS"
          location: "New York City"
          status: "Active"
        - name: "nyc-leaf-01.infra.ntc.com"
          role: "leaf"
          device_type: "vEOS"
          platform: "Arista EOS"
          location: "New York City"
          status: "Active"
        - name: "nyc-leaf-02.infra.ntc.com"
          role: "leaf"
          device_type: "vEOS"
          platform: "Arista EOS"
          location: "New York City"
          status: "Active"
        - name: "jcy-bb-01.infra.ntc.com"
          role: "backbone"
          device_type: "CSR1000V"
          platform: "Cisco IOS-XE"
          location: "Jersey City"
          status: "Active"
        - name: "jcy-rtr-01.infra.ntc.com"
          role: "router"
          device_type: "CSR1000V"
          platform: "Cisco IOS-XE"
          location: "Jersey City"
          status: "Active"
        - name: "jcy-rtr-02.infra.ntc.com"
          role: "router"
          device_type: "CSR1000V"
          platform: "Cisco IOS-XE"
          location: "Jersey City"
          status: "Active"
        - name: "jcy-spine-01.infra.ntc.com"
          role: "spine"
          device_type: "Nexus 9kv"
          platform: "Nexus NX-OS"
          location: "Jersey City"
          status: "Active"
        - name: "jcy-spine-02.infra.ntc.com"
          role: "spine"
          device_type: "Nexus 9kv"
          platform: "Nexus NX-OS"
          location: "Jersey City"
          status: "Active"
