---
- name: "ADD PREFIXES AND IPS"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    nautobot_url: "{{ lookup('env', 'NAUTOBOT_URL') }}"
    nautobot_token: "{{ lookup('env', 'NAUTOBOT_TOKEN') }}"

    interface_ips:
      - device: "jcy-bb-01.infra.ntc.com"
        interface: "Loopback0"
        address: "10.0.10.3/32"
      - device: "jcy-bb-01.infra.ntc.com"
        interface: "GigabitEthernet1"
        address: "10.0.0.15/24"
      - device: "jcy-bb-01.infra.ntc.com"
        interface: "GigabitEthernet2"
        address: "10.10.0.6/30"
      - device: "jcy-bb-01.infra.ntc.com"
        interface: "GigabitEthernet3"
        address: "10.10.0.14/30"
      - device: "jcy-bb-01.infra.ntc.com"
        interface: "GigabitEthernet4"
        address: "10.10.0.17/30"

      - device: "jcy-rtr-01.infra.ntc.com"
        interface: "Loopback0"
        address: "10.0.10.1/32"
      - device: "jcy-rtr-01.infra.ntc.com"
        interface: "GigabitEthernet1"
        address: "10.0.0.15/24"
      - device: "jcy-rtr-01.infra.ntc.com"
        interface: "GigabitEthernet2"
        address: "10.10.0.5/30"
      - device: "jcy-rtr-01.infra.ntc.com"
        interface: "GigabitEthernet4"
        address: "10.10.0.9/30"
      - device: "jcy-rtr-01.infra.ntc.com"
        interface: "GigabitEthernet5"
        address: "10.10.11.5/30"

      - device: "jcy-rtr-02.infra.ntc.com"
        interface: "Loopback0"
        address: "10.0.10.2/32"
      - device: "jcy-rtr-02.infra.ntc.com"
        interface: "GigabitEthernet1"
        address: "10.0.0.15/24"
      - device: "jcy-rtr-02.infra.ntc.com"
        interface: "GigabitEthernet3"
        address: "10.10.0.13/30"
      - device: "jcy-rtr-02.infra.ntc.com"
        interface: "GigabitEthernet4"
        address: "10.10.0.10/30"
      - device: "jcy-rtr-02.infra.ntc.com"
        interface: "GigabitEthernet5"
        address: "10.10.11.9/30"

      - device: "jcy-spine-01.infra.ntc.com"
        interface: "loopback0"
        address: "10.0.10.4/32"
      - device: "jcy-spine-01.infra.ntc.com"
        interface: "Ethernet1/1"
        address: "10.10.10.5/30"
      - device: "jcy-spine-01.infra.ntc.com"
        interface: "Ethernet1/2"
        address: "10.10.10.9/30"
      - device: "jcy-spine-01.infra.ntc.com"
        interface: "Ethernet1/3"
        address: "10.10.10.13/30"
      - device: "jcy-spine-01.infra.ntc.com"
        interface: "Ethernet1/4"
        address: "10.10.10.17/30"
      - device: "jcy-spine-01.infra.ntc.com"
        interface: "Ethernet1/5"
        address: "10.10.11.6/30"
      - device: "jcy-spine-01.infra.ntc.com"
        interface: "mgmt0"
        address: "10.0.0.15/24"

      - device: "jcy-spine-02.infra.ntc.com"
        interface: "loopback0"
        address: "10.0.10.5/32"
      - device: "jcy-spine-02.infra.ntc.com"
        interface: "Ethernet1/1"
        address: "10.10.10.6/30"
      - device: "jcy-spine-02.infra.ntc.com"
        interface: "Ethernet1/2"
        address: "10.10.10.10/30"
      - device: "jcy-spine-02.infra.ntc.com"
        interface: "Ethernet1/3"
        address: "10.10.10.14/30"
      - device: "jcy-spine-02.infra.ntc.com"
        interface: "Ethernet1/4"
        address: "10.10.10.18/30"
      - device: "jcy-spine-02.infra.ntc.com"
        interface: "Ethernet1/5"
        address: "10.10.11.10/30"
      - device: "jcy-spine-02.infra.ntc.com"
        interface: "mgmt0"
        address: "10.0.0.15/24"

      - device: "nyc-leaf-01.infra.ntc.com"
        interface: "Loopback0"
        address: "10.0.20.6/32"
      - device: "nyc-leaf-01.infra.ntc.com"
        interface: "Ethernet2"
        address: "10.11.11.14/30"
      - device: "nyc-leaf-01.infra.ntc.com"
        interface: "Ethernet3"
        address: "10.11.11.18/30"
      - device: "nyc-leaf-01.infra.ntc.com"
        interface: "Management1"
        address: "10.0.0.15/24"

      - device: "nyc-leaf-02.infra.ntc.com"
        interface: "Loopback0"
        address: "10.0.20.7/32"
      - device: "nyc-leaf-02.infra.ntc.com"
        interface: "Ethernet2"
        address: "10.11.11.18/30"
      - device: "nyc-leaf-02.infra.ntc.com"
        interface: "Ethernet3"
        address: "10.11.11.26/30"
      - device: "nyc-leaf-02.infra.ntc.com"
        interface: "Management1"
        address: "10.0.0.15/24"

      - device: "nyc-rtr-01.infra.ntc.com"
        interface: "lo0"
        address: "10.0.20.1/32"
      - device: "nyc-rtr-01.infra.ntc.com"
        interface: "ge-0/0/0"
        address: "10.10.0.21/30"
      - device: "nyc-rtr-01.infra.ntc.com"
        interface: "ge-0/0/1"
        address: "10.10.0.25/30"
      - device: "nyc-rtr-01.infra.ntc.com"
        interface: "ge-0/0/3"
        address: "10.11.11.5/30"
      - device: "nyc-rtr-01.infra.ntc.com"
        interface: "fxp0"
        address: "10.0.0.15/24"

      - device: "nyc-rtr-02.infra.ntc.com"
        interface: "lo0"
        address: "10.0.20.2/32"
      - device: "nyc-rtr-02.infra.ntc.com"
        interface: "ge-0/0/1"
        address: "10.10.0.26/30"
      - device: "nyc-rtr-02.infra.ntc.com"
        interface: "ge-0/0/2"
        address: "10.10.0.29/30"
      - device: "nyc-rtr-02.infra.ntc.com"
        interface: "ge-0/0/3"
        address: "10.11.11.9/30"
      - device: "nyc-rtr-02.infra.ntc.com"
        interface: "fxp0"
        address: "10.0.0.15/24"

      - device: "nyc-spine-01.infra.ntc.com"
        interface: "Loopback0"
        address: "10.0.20.4/32"
      - device: "nyc-spine-01.infra.ntc.com"
        interface: "Ethernet1"
        address: "10.11.11.6/30"
      - device: "nyc-spine-01.infra.ntc.com"
        interface: "Ethernet2"
        address: "10.11.11.13/30"
      - device: "nyc-spine-01.infra.ntc.com"
        interface: "Ethernet3"
        address: "10.11.11.17/30"
      - device: "nyc-spine-01.infra.ntc.com"
        interface: "Management1"
        address: "10.0.0.15/24"

      - device: "nyc-spine-02.infra.ntc.com"
        interface: "Loopback0"
        address: "10.0.20.5/32"
      - device: "nyc-spine-02.infra.ntc.com"
        interface: "Ethernet1"
        address: "10.11.11.10/30"
      - device: "nyc-spine-02.infra.ntc.com"
        interface: "Ethernet2"
        address: "10.11.11.21/30"
      - device: "nyc-spine-02.infra.ntc.com"
        interface: "Ethernet3"
        address: "10.11.11.25/30"
      - device: "nyc-spine-02.infra.ntc.com"
        interface: "Management1"
        address: "10.0.0.15/24"

      - device: "nyc-bb-01.infra.ntc.com"
        interface: "lo0"
        address: "10.0.20.3/32"
      - device: "nyc-bb-01.infra.ntc.com"
        interface: "ge-0/0/0"
        address: "10.10.0.22/30"
      - device: "nyc-bb-01.infra.ntc.com"
        interface: "ge-0/0/2"
        address: "10.10.0.30/30"
      - device: "nyc-bb-01.infra.ntc.com"
        interface: "ge-0/0/3"
        address: "10.10.0.18/30"
      - device: "nyc-bb-01.infra.ntc.com"
        interface: "fxp0"
        address: "10.0.0.15/24"

  tasks:

    - name: "ADD PREFIXES"
      networktocode.nautobot.prefix:
        url: "{{ nautobot_url }}"
        token: "{{ nautobot_token }}"
        prefix: "{{ prefix['prefix'] }}"
        status: "Active"
        type: "Container"
        namespace: "Global"
        state: present
      loop_control:
        loop_var: prefix
      loop:
        - prefix: "10.0.0.0/8"
        - prefix: "10.0.0.0/16"
        - prefix: "10.10.0.0/16"
        - prefix: "10.0.0.0/24"
        - prefix: "10.10.0.0/24"

    - name: "ADD INTERFACE IPS"
      networktocode.nautobot.ip_address:
        url: "{{ nautobot_url }}"
        token: "{{ nautobot_token }}"
        address: "{{ item['address'] }}"
        status: "Active"
        state: present
      loop: "{{ interface_ips }}"

    - name: "ASSIGN IPS TO INTERFACES"
      networktocode.nautobot.ip_address_to_interface:
        url: "{{ nautobot_url }}"
        token: "{{ nautobot_token }}"
        ip_address: "{{ ip_address['key'] }}"
        interface:
          device: "{{ item.device }}"
          name: "{{ item.interface }}"
      loop: "{{ interface_ips }}"
      vars:
        ip_address: "{{ lookup('networktocode.nautobot.lookup', 'ip-addresses', api_endpoint=nautobot_url, token=nautobot_token, api_filter='address=' ~ item.address) }}"
